### ISSUE TITLE
Map 3

### ISSUE THREAD

**Issue by matthewpurri** [rajanya/comprobfall2018-hw3#2]
https://github.com/rajanya/comprobfall2018-hw3/blob/f99ca1352abe71942cf1bd8f55b811e7e84f6f5d/turtlebot_maps/map_3.txt#L1

Should be (10,10) (10,-9) (-9,-9) (-9,10) instead

**Comment by rajanya** [comment]
You are right Matthew! Thanks for pointing this out.
