### ISSUE TITLE
Scan range wrong?

### ISSUE THREAD

**Issue by Guptajakala** [rajanya/comprobfall2018-hw3#3]
The introduction says the scan range can reach up to 10m while in the example files, scan range does not appear to be > 6m and not even in some locations that it supposed to be. 

Is the scan range wrong?

**Comment by rajanya** [comment]
Could you please take a screenshot and let us know where you feel the scan range should be >6m?

**Comment by Guptajakala** [comment]
![image](https://user-images.githubusercontent.com/40518028/49917690-24ad6080-fe6e-11e8-94f5-e590fe3867ca.png)
In Map1, the initial point in trajectory1, the max distance should be 8, but the scan are less. @rajanya 

```
scan_data: 
  ranges: [1.9969024658203125, 2.0711448192596436, 2.148198127746582, 2.2339370250701904, 2.3225631713867188, 2.421276807785034, 2.5317583084106445, 2.6560771465301514, 2.7968101501464844, 2.9440836906433105, 3.111342668533325, 3.302703619003296, 3.5234932899475098, 3.7807207107543945, 4.0565080642700195, 4.41288948059082, 4.8051934242248535, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 4.960227012634277, 4.509247303009033, 4.166668891906738, 3.85205078125, 3.7452032566070557, 3.7658636569976807, 3.789804220199585, 3.817359209060669, 3.844259262084961, 3.8749523162841797, 3.9046850204467773, 3.938375949859619, 3.9735679626464844, 2.25943660736084, 2.171790599822998, 2.09307861328125, 2.022090435028076]
```

**Comment by rajanya** [comment]
what is the orientation of the turtlebot? Could you please send out an email at comprobfall2018@gmail.com?
